package com.crossvale.oao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account_rules implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Account_rules() {
    }

}