package com.crossvale.oao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Account Number")
   private java.lang.Integer accountNBR;

   public Account()
   {
   }

   public java.lang.Integer getAccountNBR()
   {
      return this.accountNBR;
   }

   public void setAccountNBR(java.lang.Integer accountNBR)
   {
      this.accountNBR = accountNBR;
   }

   public Account(java.lang.Integer accountNBR)
   {
      this.accountNBR = accountNBR;
   }

}