package com.crossvale.oao;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Classification")
public class Classification implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("accountNumber")
   private java.lang.String accountNumber;
   @org.kie.api.definition.type.Label("product")
   private com.crossvale.oao.CodeValue product;
   @org.kie.api.definition.type.Label("subProduct")
   private com.crossvale.oao.CodeValue subProduct;
   @org.kie.api.definition.type.Label("accountStatus")
   private com.crossvale.oao.CodeValue accountStatus;
   @org.kie.api.definition.type.Label("accountExtendedStatus")
   private com.crossvale.oao.CodeValue accountExtendedStatus;

   public Classification()
   {
   }

   public java.lang.String getAccountNumber()
   {
      return this.accountNumber;
   }

   public void setAccountNumber(java.lang.String accountNumber)
   {
      this.accountNumber = accountNumber;
   }

   public com.crossvale.oao.CodeValue getProduct()
   {
      return this.product;
   }

   public void setProduct(com.crossvale.oao.CodeValue product)
   {
      this.product = product;
   }

   public com.crossvale.oao.CodeValue getSubProduct()
   {
      return this.subProduct;
   }

   public void setSubProduct(com.crossvale.oao.CodeValue subProduct)
   {
      this.subProduct = subProduct;
   }

   public com.crossvale.oao.CodeValue getAccountStatus()
   {
      return this.accountStatus;
   }

   public void setAccountStatus(
         com.crossvale.oao.CodeValue accountStatus)
   {
      this.accountStatus = accountStatus;
   }

   public com.crossvale.oao.CodeValue getAccountExtendedStatus()
   {
      return this.accountExtendedStatus;
   }

   public void setAccountExtendedStatus(
         com.crossvale.oao.CodeValue accountExtendedStatus)
   {
      this.accountExtendedStatus = accountExtendedStatus;
   }

   public Classification(java.lang.String accountNumber,
         com.crossvale.oao.CodeValue product,
         com.crossvale.oao.CodeValue subProduct,
         com.crossvale.oao.CodeValue accountStatus,
         com.crossvale.oao.CodeValue accountExtendedStatus)
   {
      this.accountNumber = accountNumber;
      this.product = product;
      this.subProduct = subProduct;
      this.accountStatus = accountStatus;
      this.accountExtendedStatus = accountExtendedStatus;
   }

}