package com.crossvale.oao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Credit_Rating implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Credit_Rating() {
    }

}