package com.crossvale.oao;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("crossSale")
public class CrossSale implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "customerType")
   private java.lang.String customerType;
   @org.kie.api.definition.type.Label(value = "creditScore")
   private java.lang.Integer creditScore;

   public CrossSale()
   {
   }

   public java.lang.String getCustomerType()
   {
      return this.customerType;
   }

   public void setCustomerType(java.lang.String customerType)
   {
      this.customerType = customerType;
   }

   public java.lang.Integer getCreditScore()
   {
      return this.creditScore;
   }

   public void setCreditScore(java.lang.Integer creditScore)
   {
      this.creditScore = creditScore;
   }

   public CrossSale(java.lang.String customerType,
         java.lang.Integer creditScore)
   {
      this.customerType = customerType;
      this.creditScore = creditScore;
   }

}