package com.crossvale.oao;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Customer")
/*@JsonIgnoreProperties(ignoreUnknown = true)*/
public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("email")
   private java.lang.String email;

   @org.kie.api.definition.type.Label("alternatePhoneNumber")
   private java.lang.String alternatePhoneNumber;

   @org.kie.api.definition.type.Label("countryCode")
   private java.lang.String countryCode;

   @org.kie.api.definition.type.Label("address")
   private com.crossvale.oao.Address address;

   @org.kie.api.definition.type.Label("identification")
   private com.crossvale.oao.Identification identification;

   @org.kie.api.definition.type.Label("user_id")
   private java.lang.String user_id;

   @org.kie.api.definition.type.Label("customer_number")
   private java.lang.String customer_number;

   @org.kie.api.definition.type.Label("legal_name")
   private java.lang.String legal_name;

   @org.kie.api.definition.type.Label("mobile_phone_number")
   private java.lang.String mobile_phone_number;

   @org.kie.api.definition.type.Label("date_of_birth")
   private java.lang.String date_of_birth;

   @org.kie.api.definition.type.Label("relationship_status")
   private java.lang.String relationship_status;

   @org.kie.api.definition.type.Label("highest_education_attained")
   private java.lang.String highest_education_attained;

   @org.kie.api.definition.type.Label("employment_status")
   private java.lang.String employment_status;

   @org.kie.api.definition.type.Label("kyc_status")
   private java.lang.String kyc_status;

   @org.kie.api.definition.type.Label("last_ok_date")
   private java.lang.String last_ok_date;

   @org.kie.api.definition.type.Label("accounts")
   private java.util.List<com.crossvale.oao.Accounts> accounts;

   @org.kie.api.definition.type.Label(value = "credit_rating")
   private com.crossvale.oao.Credit_Rating credit_rating;

   @org.kie.api.definition.type.Label(value = "credit_limit")
   private com.crossvale.oao.CreditLimit credit_limit;

   public Customer()
   {
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getAlternatePhoneNumber()
   {
      return this.alternatePhoneNumber;
   }

   public void setAlternatePhoneNumber(java.lang.String alternatePhoneNumber)
   {
      this.alternatePhoneNumber = alternatePhoneNumber;
   }

   public java.lang.String getCountryCode()
   {
      return this.countryCode;
   }

   public void setCountryCode(java.lang.String countryCode)
   {
      this.countryCode = countryCode;
   }

   public com.crossvale.oao.Address getAddress()
   {
      return this.address;
   }

   public void setAddress(com.crossvale.oao.Address address)
   {
      this.address = address;
   }

   public com.crossvale.oao.Identification getIdentification()
   {
      return this.identification;
   }

   public void setIdentification(com.crossvale.oao.Identification identification)
   {
      this.identification = identification;
   }

   public java.lang.String getUser_id()
   {
      return this.user_id;
   }

   public void setUser_id(java.lang.String user_id)
   {
      this.user_id = user_id;
   }

   public java.lang.String getCustomer_number()
   {
      return this.customer_number;
   }

   public void setCustomer_number(java.lang.String customer_number)
   {
      this.customer_number = customer_number;
   }

   public java.lang.String getLegal_name()
   {
      return this.legal_name;
   }

   public void setLegal_name(java.lang.String legal_name)
   {
      this.legal_name = legal_name;
   }

   public java.lang.String getMobile_phone_number()
   {
      return this.mobile_phone_number;
   }

   public void setMobile_phone_number(java.lang.String mobile_phone_number)
   {
      this.mobile_phone_number = mobile_phone_number;
   }

   public java.lang.String getDate_of_birth()
   {
      return this.date_of_birth;
   }

   public void setDate_of_birth(java.lang.String date_of_birth)
   {
      this.date_of_birth = date_of_birth;
   }

   public java.lang.String getRelationship_status()
   {
      return this.relationship_status;
   }

   public void setRelationship_status(java.lang.String relationship_status)
   {
      this.relationship_status = relationship_status;
   }

   public java.lang.String getHighest_education_attained()
   {
      return this.highest_education_attained;
   }

   public void setHighest_education_attained(
         java.lang.String highest_education_attained)
   {
      this.highest_education_attained = highest_education_attained;
   }

   public java.lang.String getEmployment_status()
   {
      return this.employment_status;
   }

   public void setEmployment_status(java.lang.String employment_status)
   {
      this.employment_status = employment_status;
   }

   public java.lang.String getKyc_status()
   {
      return this.kyc_status;
   }

   public void setKyc_status(java.lang.String kyc_status)
   {
      this.kyc_status = kyc_status;
   }

   public java.lang.String getLast_ok_date()
   {
      return this.last_ok_date;
   }

   public void setLast_ok_date(java.lang.String last_ok_date)
   {
      this.last_ok_date = last_ok_date;
   }

   public java.util.List<com.crossvale.oao.Accounts> getAccounts()
   {
      return this.accounts;
   }

   public void setAccounts(java.util.List<com.crossvale.oao.Accounts> accounts)
   {
      this.accounts = accounts;
   }

   public com.crossvale.oao.Credit_Rating getCredit_rating()
   {
      return this.credit_rating;
   }

   public void setCredit_rating(com.crossvale.oao.Credit_Rating credit_rating)
   {
      this.credit_rating = credit_rating;
   }

   public com.crossvale.oao.CreditLimit getCredit_limit()
   {
      return this.credit_limit;
   }

   public void setCredit_limit(com.crossvale.oao.CreditLimit credit_limit)
   {
      this.credit_limit = credit_limit;
   }

   public Customer(java.lang.String email, java.lang.String alternatePhoneNumber,
         java.lang.String countryCode, com.crossvale.oao.Address address,
         com.crossvale.oao.Identification identification,
         java.lang.String user_id, java.lang.String customer_number,
         java.lang.String legal_name, java.lang.String mobile_phone_number,
         java.lang.String date_of_birth, java.lang.String relationship_status,
         java.lang.String highest_education_attained,
         java.lang.String employment_status, java.lang.String kyc_status,
         java.lang.String last_ok_date,
         java.util.List<com.crossvale.oao.Accounts> accounts,
         com.crossvale.oao.Credit_Rating credit_rating,
         com.crossvale.oao.CreditLimit credit_limit)
   {
      this.email = email;
      this.alternatePhoneNumber = alternatePhoneNumber;
      this.countryCode = countryCode;
      this.address = address;
      this.identification = identification;
      this.user_id = user_id;
      this.customer_number = customer_number;
      this.legal_name = legal_name;
      this.mobile_phone_number = mobile_phone_number;
      this.date_of_birth = date_of_birth;
      this.relationship_status = relationship_status;
      this.highest_education_attained = highest_education_attained;
      this.employment_status = employment_status;
      this.kyc_status = kyc_status;
      this.last_ok_date = last_ok_date;
      this.accounts = accounts;
      this.credit_rating = credit_rating;
      this.credit_limit = credit_limit;
   }

}