package com.crossvale.oao;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Customer")
public class Customer implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Email")
   private java.lang.String email;

   @org.kie.api.definition.type.Label("customerNumber")
   private java.lang.String customerNumber;

   @org.kie.api.definition.type.Label(value = "KYC Status")
   private java.lang.String kycStatus;

   @org.kie.api.definition.type.Label(value = "User ID")
   private java.lang.String userId;

   @org.kie.api.definition.type.Label(value = "Last OK Date")
   private java.util.Date lastOkDate;

   @org.kie.api.definition.type.Label(value = "Date of Birth")
   private java.util.Date dateOfBirth;

   @org.kie.api.definition.type.Label(value = "Legal Name")
   private java.lang.String legalName;

   @org.kie.api.definition.type.Label(value = "Mobile Phone Number")
   private java.lang.String mobilePhoneNumber;

   @org.kie.api.definition.type.Label(value = "Relationship Status")
   private java.lang.String relationshipStatus;

   @org.kie.api.definition.type.Label(value = "Credit Rating")
   private java.lang.String creditRating;

   @org.kie.api.definition.type.Label(value = "Credit Limit")
   private java.lang.String creditLimit;

   @org.kie.api.definition.type.Label(value = "Highest Education Attained")
   private java.lang.String highestEducationAttained;

   @org.kie.api.definition.type.Label(value = "Employment Status")
   private java.lang.String employmentStatus;

   public Customer()
   {
   }

   public java.lang.String getEmail()
   {
      return this.email;
   }

   public void setEmail(java.lang.String email)
   {
      this.email = email;
   }

   public java.lang.String getCustomerNumber()
   {
      return this.customerNumber;
   }

   public void setCustomerNumber(java.lang.String customerNumber)
   {
      this.customerNumber = customerNumber;
   }

   public java.lang.String getKycStatus()
   {
      return this.kycStatus;
   }

   public void setKycStatus(java.lang.String kycStatus)
   {
      this.kycStatus = kycStatus;
   }

   public java.lang.String getUserId()
   {
      return this.userId;
   }

   public void setUserId(java.lang.String userId)
   {
      this.userId = userId;
   }

   public java.util.Date getLastOkDate()
   {
      return this.lastOkDate;
   }

   public void setLastOkDate(java.util.Date lastOkDate)
   {
      this.lastOkDate = lastOkDate;
   }

   public java.util.Date getDateOfBirth()
   {
      return this.dateOfBirth;
   }

   public void setDateOfBirth(java.util.Date dateOfBirth)
   {
      this.dateOfBirth = dateOfBirth;
   }

   public java.lang.String getLegalName()
   {
      return this.legalName;
   }

   public void setLegalName(java.lang.String legalName)
   {
      this.legalName = legalName;
   }

   public java.lang.String getMobilePhoneNumber()
   {
      return this.mobilePhoneNumber;
   }

   public void setMobilePhoneNumber(java.lang.String mobilePhoneNumber)
   {
      this.mobilePhoneNumber = mobilePhoneNumber;
   }

   public java.lang.String getRelationshipStatus()
   {
      return this.relationshipStatus;
   }

   public void setRelationshipStatus(java.lang.String relationshipStatus)
   {
      this.relationshipStatus = relationshipStatus;
   }

   public java.lang.String getCreditRating()
   {
      return this.creditRating;
   }

   public void setCreditRating(java.lang.String creditRating)
   {
      this.creditRating = creditRating;
   }

   public java.lang.String getCreditLimit()
   {
      return this.creditLimit;
   }

   public void setCreditLimit(java.lang.String creditLimit)
   {
      this.creditLimit = creditLimit;
   }

   public java.lang.String getHighestEducationAttained()
   {
      return this.highestEducationAttained;
   }

   public void setHighestEducationAttained(
         java.lang.String highestEducationAttained)
   {
      this.highestEducationAttained = highestEducationAttained;
   }

   public java.lang.String getEmploymentStatus()
   {
      return this.employmentStatus;
   }

   public void setEmploymentStatus(java.lang.String employmentStatus)
   {
      this.employmentStatus = employmentStatus;
   }

   public Customer(java.lang.String email, java.lang.String customerNumber,
         java.lang.String kycStatus, java.lang.String userId,
         java.util.Date lastOkDate, java.util.Date dateOfBirth,
         java.lang.String legalName, java.lang.String mobilePhoneNumber,
         java.lang.String relationshipStatus, java.lang.String creditRating,
         java.lang.String creditLimit,
         java.lang.String highestEducationAttained,
         java.lang.String employmentStatus)
   {
      this.email = email;
      this.customerNumber = customerNumber;
      this.kycStatus = kycStatus;
      this.userId = userId;
      this.lastOkDate = lastOkDate;
      this.dateOfBirth = dateOfBirth;
      this.legalName = legalName;
      this.mobilePhoneNumber = mobilePhoneNumber;
      this.relationshipStatus = relationshipStatus;
      this.creditRating = creditRating;
      this.creditLimit = creditLimit;
      this.highestEducationAttained = highestEducationAttained;
      this.employmentStatus = employmentStatus;
   }

}