package com.crossvale.oao;
package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("KeyValueParam")
public class KeyValueParam implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "key")
   private com.crossvale.carddispute.CodeValue key;
   @org.kie.api.definition.type.Label(value = "value")
   private com.crossvale.carddispute.CodeValue value;

   public KeyValueParam()
   {
   }

   public com.crossvale.carddispute.CodeValue getKey()
   {
      return this.key;
   }

   public void setKey(com.crossvale.carddispute.CodeValue key)
   {
      this.key = key;
   }

   public com.crossvale.carddispute.CodeValue getValue()
   {
      return this.value;
   }

   public void setValue(com.crossvale.carddispute.CodeValue value)
   {
      this.value = value;
   }

   public KeyValueParam(com.crossvale.carddispute.CodeValue key,
         com.crossvale.carddispute.CodeValue value)
   {
      this.key = key;
      this.value = value;
   }

}