package com.crossvale.oao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PostAccount implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public PostAccount() {
    }

}