package com.crossvale.oao;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PostAccount implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "customerNumber")
   private java.lang.String customerNumber;
   @org.kie.api.definition.type.Label(value = "label")
   private java.lang.String label;
   @org.kie.api.definition.type.Label(value = "type")
   private java.lang.String type;
   @org.kie.api.definition.type.Label(value = "branch_id")
   private java.lang.String branch_id;

   public PostAccount()
   {
   }

   public java.lang.String getCustomerNumber()
   {
      return this.customerNumber;
   }

   public void setCustomerNumber(java.lang.String customerNumber)
   {
      this.customerNumber = customerNumber;
   }

   public java.lang.String getLabel()
   {
      return this.label;
   }

   public void setLabel(java.lang.String label)
   {
      this.label = label;
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getBranch_id()
   {
      return this.branch_id;
   }

   public void setBranch_id(java.lang.String branch_id)
   {
      this.branch_id = branch_id;
   }

   public PostAccount(java.lang.String customerNumber, java.lang.String label,
         java.lang.String type, java.lang.String branch_id)
   {
      this.customerNumber = customerNumber;
      this.label = label;
      this.type = type;
      this.branch_id = branch_id;
   }

}