package com.crossvale.oao;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Task")
public class Task implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("taskNumber")
   private java.lang.String taskNumber;
   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("taskCode")
   private java.lang.String taskCode;

   @org.kie.api.definition.type.Label("customData")
   private java.lang.String customData;

   @org.kie.api.definition.type.Label("slaDate")
   private String slaDate;

   @org.kie.api.definition.type.Label("taskBpm")
   private java.lang.String taskBpm;

   @org.kie.api.definition.type.Label("createdDate")
   private String createdDate;

   @org.kie.api.definition.type.Label("status")
   private com.crossvale.oao.CodeValue status;

   @org.kie.api.definition.type.Label("assignTo")
   private com.crossvale.oao.AssignTo assignTo;

   @org.kie.api.definition.type.Label("slaStatus")
   private com.crossvale.oao.CodeValue slaStatus;

   @org.kie.api.definition.type.Label("audit")
   private com.crossvale.oao.Audit audit;

   public Task()
   {
   }

   public java.lang.String getTaskNumber()
   {
      return this.taskNumber;
   }

   public void setTaskNumber(java.lang.String taskNumber)
   {
      this.taskNumber = taskNumber;
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getTaskCode()
   {
      return this.taskCode;
   }

   public void setTaskCode(java.lang.String taskCode)
   {
      this.taskCode = taskCode;
   }

   public java.lang.String getCustomData()
   {
      return this.customData;
   }

   public void setCustomData(java.lang.String customData)
   {
      this.customData = customData;
   }

   public java.lang.String getTaskBpm()
   {
      return this.taskBpm;
   }

   public void setTaskBpm(java.lang.String taskBpm)
   {
      this.taskBpm = taskBpm;
   }

   public com.crossvale.oao.CodeValue getStatus()
   {
      return this.status;
   }

   public void setStatus(com.crossvale.oao.CodeValue status)
   {
      this.status = status;
   }

   public com.crossvale.oao.AssignTo getAssignTo()
   {
      return this.assignTo;
   }

   public void setAssignTo(com.crossvale.oao.AssignTo assignTo)
   {
      this.assignTo = assignTo;
   }

   public com.crossvale.oao.CodeValue getSlaStatus()
   {
      return this.slaStatus;
   }

   public void setSlaStatus(com.crossvale.oao.CodeValue slaStatus)
   {
      this.slaStatus = slaStatus;
   }

   public com.crossvale.oao.Audit getAudit()
   {
      return this.audit;
   }

   public void setAudit(com.crossvale.oao.Audit audit)
   {
      this.audit = audit;
   }

   public java.lang.String getCreatedDate()
   {
      return this.createdDate;
   }

   public void setCreatedDate(java.lang.String createdDate)
   {
      this.createdDate = createdDate;
   }

   public java.lang.String getSlaDate()
   {
      return this.slaDate;
   }

   public void setSlaDate(java.lang.String slaDate)
   {
      this.slaDate = slaDate;
   }

   public Task(java.lang.String taskNumber, java.lang.String ticketNumber,
         java.lang.String taskCode, java.lang.String customData,
         java.lang.String slaDate, java.lang.String taskBpm,
         java.lang.String createdDate,
         com.crossvale.oao.CodeValue status,
         com.crossvale.oao.AssignTo assignTo,
         com.crossvale.oao.CodeValue slaStatus,
         com.crossvale.oao.Audit audit)
   {
      this.taskNumber = taskNumber;
      this.ticketNumber = ticketNumber;
      this.taskCode = taskCode;
      this.customData = customData;
      this.slaDate = slaDate;
      this.taskBpm = taskBpm;
      this.createdDate = createdDate;
      this.status = status;
      this.assignTo = assignTo;
      this.slaStatus = slaStatus;
      this.audit = audit;
   }

}