package com.crossvale.oao;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Ticket")
public class Ticket implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("narrative")
   private java.lang.String narrative;
   @org.kie.api.definition.type.Label("accountNumber")
   private java.lang.String accountNumber;
   @org.kie.api.definition.type.Label("customerNumber")
   private java.lang.String customerNumber;

   @org.kie.api.definition.type.Label("customer")
   private com.crossvale.oao.Customer customer;

   @org.kie.api.definition.type.Label("complaintFlag")
   private java.lang.String complaintFlag;

   @org.kie.api.definition.type.Label("approvalFlag")
   private java.lang.String approvalFlag;

   @org.kie.api.definition.type.Label("securityLevelCode")
   private java.lang.String securityLevelCode;

   @org.kie.api.definition.type.Label("createdDate")
   private java.util.Date createdDate;

   @org.kie.api.definition.type.Label("receivedDate")
   private java.util.Date receivedDate;

   @org.kie.api.definition.type.Label("assignTo")
   private com.crossvale.oao.AssignTo assignTo;

   @org.kie.api.definition.type.Label("audit")
   private com.crossvale.oao.Audit audit;

   @org.kie.api.definition.type.Label("category")
   private com.crossvale.oao.CodeValue category;

   @org.kie.api.definition.type.Label("item")
   private com.crossvale.oao.CodeValue item;

   @org.kie.api.definition.type.Label("status")
   private com.crossvale.oao.CodeValue status;

   @org.kie.api.definition.type.Label("severity")
   private com.crossvale.oao.CodeValue severity;

   @org.kie.api.definition.type.Label("priority")
   private com.crossvale.oao.CodeValue priority;

   @org.kie.api.definition.type.Label("originator")
   private com.crossvale.oao.Originator originator;

   @org.kie.api.definition.type.Label("requestor")
   private com.crossvale.oao.Requestor requestor;

   @org.kie.api.definition.type.Label("contactMethod")
   private com.crossvale.oao.ContactMethod contactMethod;

   @org.kie.api.definition.type.Label("classification")
   private com.crossvale.oao.Classification classification;

   @org.kie.api.definition.type.Label("transactionList")
   private java.util.List<com.crossvale.oao.Transaction> transactionList;

   @org.kie.api.definition.type.Label("attributeList")
   private java.util.List<com.crossvale.oao.Attribute> attributeList;

   @org.kie.api.definition.type.Label("attachmentList")
   private java.util.List<com.crossvale.oao.Attachment> attachmentList;

   @org.kie.api.definition.type.Label("actionList")
   private java.util.List<com.crossvale.oao.Action> actionList;

   @org.kie.api.definition.type.Label("taskList")
   private java.util.List<com.crossvale.oao.Task> taskList;

   @org.kie.api.definition.type.Label(value = "sla")
   private java.lang.String sla;

   public Ticket()
   {
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getNarrative()
   {
      return this.narrative;
   }

   public void setNarrative(java.lang.String narrative)
   {
      this.narrative = narrative;
   }

   public java.lang.String getAccountNumber()
   {
      return this.accountNumber;
   }

   public void setAccountNumber(java.lang.String accountNumber)
   {
      this.accountNumber = accountNumber;
   }

   public java.lang.String getCustomerNumber()
   {
      return this.customerNumber;
   }

   public void setCustomerNumber(java.lang.String customerNumber)
   {
      this.customerNumber = customerNumber;
   }

   public com.crossvale.oao.Customer getCustomer()
   {
      return this.customer;
   }

   public void setCustomer(com.crossvale.oao.Customer customer)
   {
      this.customer = customer;
   }

   public java.lang.String getComplaintFlag()
   {
      return this.complaintFlag;
   }

   public void setComplaintFlag(java.lang.String complaintFlag)
   {
      this.complaintFlag = complaintFlag;
   }

   public java.lang.String getApprovalFlag()
   {
      return this.approvalFlag;
   }

   public void setApprovalFlag(java.lang.String approvalFlag)
   {
      this.approvalFlag = approvalFlag;
   }

   public java.lang.String getSecurityLevelCode()
   {
      return this.securityLevelCode;
   }

   public void setSecurityLevelCode(java.lang.String securityLevelCode)
   {
      this.securityLevelCode = securityLevelCode;
   }

   public java.util.Date getCreatedDate()
   {
      return this.createdDate;
   }

   public void setCreatedDate(java.util.Date createdDate)
   {
      this.createdDate = createdDate;
   }

   public java.util.Date getReceivedDate()
   {
      return this.receivedDate;
   }

   public void setReceivedDate(java.util.Date receivedDate)
   {
      this.receivedDate = receivedDate;
   }

   public com.crossvale.oao.AssignTo getAssignTo()
   {
      return this.assignTo;
   }

   public void setAssignTo(com.crossvale.oao.AssignTo assignTo)
   {
      this.assignTo = assignTo;
   }

   public com.crossvale.oao.Audit getAudit()
   {
      return this.audit;
   }

   public void setAudit(com.crossvale.oao.Audit audit)
   {
      this.audit = audit;
   }

   public com.crossvale.oao.CodeValue getCategory()
   {
      return this.category;
   }

   public void setCategory(com.crossvale.oao.CodeValue category)
   {
      this.category = category;
   }

   public com.crossvale.oao.CodeValue getItem()
   {
      return this.item;
   }

   public void setItem(com.crossvale.oao.CodeValue item)
   {
      this.item = item;
   }

   public com.crossvale.oao.CodeValue getStatus()
   {
      return this.status;
   }

   public void setStatus(com.crossvale.oao.CodeValue status)
   {
      this.status = status;
   }

   public com.crossvale.oao.CodeValue getSeverity()
   {
      return this.severity;
   }

   public void setSeverity(com.crossvale.oao.CodeValue severity)
   {
      this.severity = severity;
   }

   public com.crossvale.oao.CodeValue getPriority()
   {
      return this.priority;
   }

   public void setPriority(com.crossvale.oao.CodeValue priority)
   {
      this.priority = priority;
   }

   public com.crossvale.oao.Originator getOriginator()
   {
      return this.originator;
   }

   public void setOriginator(com.crossvale.oao.Originator originator)
   {
      this.originator = originator;
   }

   public com.crossvale.oao.Requestor getRequestor()
   {
      return this.requestor;
   }

   public void setRequestor(com.crossvale.oao.Requestor requestor)
   {
      this.requestor = requestor;
   }

   public com.crossvale.oao.ContactMethod getContactMethod()
   {
      return this.contactMethod;
   }

   public void setContactMethod(
         com.crossvale.oao.ContactMethod contactMethod)
   {
      this.contactMethod = contactMethod;
   }

   public com.crossvale.oao.Classification getClassification()
   {
      return this.classification;
   }

   public void setClassification(
         com.crossvale.oao.Classification classification)
   {
      this.classification = classification;
   }

   public java.util.List<com.crossvale.oao.Transaction> getTransactionList()
   {
      return this.transactionList;
   }

   public void setTransactionList(
         java.util.List<com.crossvale.oao.Transaction> transactionList)
   {
      this.transactionList = transactionList;
   }

   public java.util.List<com.crossvale.oao.Attribute> getAttributeList()
   {
      return this.attributeList;
   }

   public void setAttributeList(
         java.util.List<com.crossvale.oao.Attribute> attributeList)
   {
      this.attributeList = attributeList;
   }

   public java.util.List<com.crossvale.oao.Attachment> getAttachmentList()
   {
      return this.attachmentList;
   }

   public void setAttachmentList(
         java.util.List<com.crossvale.oao.Attachment> attachmentList)
   {
      this.attachmentList = attachmentList;
   }

   public java.util.List<com.crossvale.oao.Action> getActionList()
   {
      return this.actionList;
   }

   public void setActionList(
         java.util.List<com.crossvale.oao.Action> actionList)
   {
      this.actionList = actionList;
   }

   public java.util.List<com.crossvale.oao.Task> getTaskList()
   {
      return this.taskList;
   }

   public void setTaskList(java.util.List<com.crossvale.oao.Task> taskList)
   {
      this.taskList = taskList;
   }

   public java.lang.String getSla()
   {
      return this.sla;
   }

   public void setSla(java.lang.String sla)
   {
      this.sla = sla;
   }

   public Ticket(java.lang.String ticketNumber, java.lang.String narrative,
         java.lang.String accountNumber, java.lang.String customerNumber,
         com.crossvale.oao.Customer customer,
         java.lang.String complaintFlag, java.lang.String approvalFlag,
         java.lang.String securityLevelCode, java.util.Date createdDate,
         java.util.Date receivedDate,
         com.crossvale.oao.AssignTo assignTo,
         com.crossvale.oao.Audit audit,
         com.crossvale.oao.CodeValue category,
         com.crossvale.oao.CodeValue item,
         com.crossvale.oao.CodeValue status,
         com.crossvale.oao.CodeValue severity,
         com.crossvale.oao.CodeValue priority,
         com.crossvale.oao.Originator originator,
         com.crossvale.oao.Requestor requestor,
         com.crossvale.oao.ContactMethod contactMethod,
         com.crossvale.oao.Classification classification,
         java.util.List<com.crossvale.oao.Transaction> transactionList,
         java.util.List<com.crossvale.oao.Attribute> attributeList,
         java.util.List<com.crossvale.oao.Attachment> attachmentList,
         java.util.List<com.crossvale.oao.Action> actionList,
         java.util.List<com.crossvale.oao.Task> taskList,
         java.lang.String sla)
   {
      this.ticketNumber = ticketNumber;
      this.narrative = narrative;
      this.accountNumber = accountNumber;
      this.customerNumber = customerNumber;
      this.customer = customer;
      this.complaintFlag = complaintFlag;
      this.approvalFlag = approvalFlag;
      this.securityLevelCode = securityLevelCode;
      this.createdDate = createdDate;
      this.receivedDate = receivedDate;
      this.assignTo = assignTo;
      this.audit = audit;
      this.category = category;
      this.item = item;
      this.status = status;
      this.severity = severity;
      this.priority = priority;
      this.originator = originator;
      this.requestor = requestor;
      this.contactMethod = contactMethod;
      this.classification = classification;
      this.transactionList = transactionList;
      this.attributeList = attributeList;
      this.attachmentList = attachmentList;
      this.actionList = actionList;
      this.taskList = taskList;
      this.sla = sla;
   }

}