package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account_routing implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Account_routing() {
    }

}