package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "applicationNumber")
   private java.lang.String applicationNumber;
   @org.kie.api.definition.type.Label(value = "customerNumber")
   private java.lang.String customerNumber;
   @org.kie.api.definition.type.Label(value = "identity")
   private com.crossvale.common.Account_rules identity;

   public Application()
   {
   }

   public java.lang.String getApplicationNumber()
   {
      return this.applicationNumber;
   }

   public void setApplicationNumber(java.lang.String applicationNumber)
   {
      this.applicationNumber = applicationNumber;
   }

   public java.lang.String getCustomerNumber()
   {
      return this.customerNumber;
   }

   public void setCustomerNumber(java.lang.String customerNumber)
   {
      this.customerNumber = customerNumber;
   }

   public com.crossvale.common.Account_rules getIdentity()
   {
      return this.identity;
   }

   public void setIdentity(com.crossvale.common.Account_rules identity)
   {
      this.identity = identity;
   }

   public Application(java.lang.String applicationNumber,
         java.lang.String customerNumber,
         com.crossvale.common.Account_rules identity)
   {
      this.applicationNumber = applicationNumber;
      this.customerNumber = customerNumber;
      this.identity = identity;
   }

}