package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AssignTo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "user")
   private com.crossvale.common.CodeValue user;
   @org.kie.api.definition.type.Label(value = "group")
   private com.crossvale.common.CodeValue group;
   @org.kie.api.definition.type.Label(value = "firstName")
   private java.lang.String firstName;
   @org.kie.api.definition.type.Label(value = "lastName")
   private java.lang.String lastName;

   public AssignTo()
   {
   }

   public com.crossvale.common.CodeValue getUser()
   {
      return this.user;
   }

   public void setUser(com.crossvale.common.CodeValue user)
   {
      this.user = user;
   }

   public com.crossvale.common.CodeValue getGroup()
   {
      return this.group;
   }

   public void setGroup(com.crossvale.common.CodeValue group)
   {
      this.group = group;
   }

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public AssignTo(com.crossvale.common.CodeValue user,
         com.crossvale.common.CodeValue group, java.lang.String firstName,
         java.lang.String lastName)
   {
      this.user = user;
      this.group = group;
      this.firstName = firstName;
      this.lastName = lastName;
   }

}