package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Balance implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Balance() {
    }

}