package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CodeValue implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "code")
   private java.lang.String code;
   @org.kie.api.definition.type.Label(value = "value")
   private java.lang.String value;

   public CodeValue()
   {
   }

   public java.lang.String getCode()
   {
      return this.code;
   }

   public void setCode(java.lang.String code)
   {
      this.code = code;
   }

   public java.lang.String getValue()
   {
      return this.value;
   }

   public void setValue(java.lang.String value)
   {
      this.value = value;
   }

   public CodeValue(java.lang.String code, java.lang.String value)
   {
      this.code = code;
      this.value = value;
   }

}