package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class creditRating implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public creditRating() {
    }

}