package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Crossale implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Crossale() {
    }

}