package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class KeyValueParam implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "key")
   private com.crossvale.common.CodeValue key;
   @org.kie.api.definition.type.Label(value = "value")
   private com.crossvale.common.CodeValue value;

   public KeyValueParam()
   {
   }

   public com.crossvale.common.CodeValue getKey()
   {
      return this.key;
   }

   public void setKey(com.crossvale.common.CodeValue key)
   {
      this.key = key;
   }

   public com.crossvale.common.CodeValue getValue()
   {
      return this.value;
   }

   public void setValue(com.crossvale.common.CodeValue value)
   {
      this.value = value;
   }

   public KeyValueParam(com.crossvale.common.CodeValue key,
         com.crossvale.common.CodeValue value)
   {
      this.key = key;
      this.value = value;
   }

}