package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ticket implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("narrative")
   private java.lang.String narrative;
   @org.kie.api.definition.type.Label("complaintFlag")
   private java.lang.String complaintFlag;
   @org.kie.api.definition.type.Label("approvalFlag")
   private java.lang.String approvalFlag;
   @org.kie.api.definition.type.Label("securityLevelCode")
   private java.lang.String securityLevelCode;
   @org.kie.api.definition.type.Label("createdDate")
   private java.lang.String createdDate;
   @org.kie.api.definition.type.Label("receivedDate")
   private java.lang.String receivedDate;
   @org.kie.api.definition.type.Label("assignTo")
   private com.crossvale.common.AssignTo assignTo;
   @org.kie.api.definition.type.Label("audit")
   private com.crossvale.common.Audit audit;
   @org.kie.api.definition.type.Label("category")
   private com.crossvale.common.CodeValue category;
   @org.kie.api.definition.type.Label("item")
   private com.crossvale.common.CodeValue item;
   @org.kie.api.definition.type.Label("status")
   private com.crossvale.common.CodeValue status;
   @org.kie.api.definition.type.Label("severity")
   private com.crossvale.common.CodeValue severity;
   @org.kie.api.definition.type.Label("priority")
   private com.crossvale.common.CodeValue priority;
   @org.kie.api.definition.type.Label("originator")
   private com.crossvale.common.Originator originator;
   @org.kie.api.definition.type.Label("requestor")
   private com.crossvale.common.Requestor requestor;
   @org.kie.api.definition.type.Label("contactMethod")
   private com.crossvale.common.ContactMethod contactMethod;
   @org.kie.api.definition.type.Label("classification")
   private com.crossvale.common.Classification classification;
   @org.kie.api.definition.type.Label("transactionList")
   private java.util.List<com.crossvale.common.Transaction> transactionList;
   @org.kie.api.definition.type.Label("attributeList")
   private java.util.List<com.crossvale.common.Attribute> attributeList;
   @org.kie.api.definition.type.Label("attachmentList")
   private java.util.List<com.crossvale.common.Attachment> attachmentList;
   @org.kie.api.definition.type.Label("actionList")
   private java.util.List<com.crossvale.common.Action> actionList;
   @org.kie.api.definition.type.Label("sla")
   private java.lang.String sla;

   @org.kie.api.definition.type.Label(value = "taskList")
   private java.util.List<com.crossvale.common.Task> taskList;

   public Ticket()
   {
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getNarrative()
   {
      return this.narrative;
   }

   public void setNarrative(java.lang.String narrative)
   {
      this.narrative = narrative;
   }

   public java.lang.String getComplaintFlag()
   {
      return this.complaintFlag;
   }

   public void setComplaintFlag(java.lang.String complaintFlag)
   {
      this.complaintFlag = complaintFlag;
   }

   public java.lang.String getApprovalFlag()
   {
      return this.approvalFlag;
   }

   public void setApprovalFlag(java.lang.String approvalFlag)
   {
      this.approvalFlag = approvalFlag;
   }

   public java.lang.String getSecurityLevelCode()
   {
      return this.securityLevelCode;
   }

   public void setSecurityLevelCode(java.lang.String securityLevelCode)
   {
      this.securityLevelCode = securityLevelCode;
   }

   public java.lang.String getCreatedDate()
   {
      return this.createdDate;
   }

   public void setCreatedDate(java.lang.String createdDate)
   {
      this.createdDate = createdDate;
   }

   public java.lang.String getReceivedDate()
   {
      return this.receivedDate;
   }

   public void setReceivedDate(java.lang.String receivedDate)
   {
      this.receivedDate = receivedDate;
   }

   public com.crossvale.common.AssignTo getAssignTo()
   {
      return this.assignTo;
   }

   public void setAssignTo(com.crossvale.common.AssignTo assignTo)
   {
      this.assignTo = assignTo;
   }

   public com.crossvale.common.Audit getAudit()
   {
      return this.audit;
   }

   public void setAudit(com.crossvale.common.Audit audit)
   {
      this.audit = audit;
   }

   public com.crossvale.common.CodeValue getCategory()
   {
      return this.category;
   }

   public void setCategory(com.crossvale.common.CodeValue category)
   {
      this.category = category;
   }

   public com.crossvale.common.CodeValue getItem()
   {
      return this.item;
   }

   public void setItem(com.crossvale.common.CodeValue item)
   {
      this.item = item;
   }

   public com.crossvale.common.CodeValue getStatus()
   {
      return this.status;
   }

   public void setStatus(com.crossvale.common.CodeValue status)
   {
      this.status = status;
   }

   public com.crossvale.common.CodeValue getSeverity()
   {
      return this.severity;
   }

   public void setSeverity(com.crossvale.common.CodeValue severity)
   {
      this.severity = severity;
   }

   public com.crossvale.common.CodeValue getPriority()
   {
      return this.priority;
   }

   public void setPriority(com.crossvale.common.CodeValue priority)
   {
      this.priority = priority;
   }

   public com.crossvale.common.Originator getOriginator()
   {
      return this.originator;
   }

   public void setOriginator(com.crossvale.common.Originator originator)
   {
      this.originator = originator;
   }

   public com.crossvale.common.Requestor getRequestor()
   {
      return this.requestor;
   }

   public void setRequestor(com.crossvale.common.Requestor requestor)
   {
      this.requestor = requestor;
   }

   public com.crossvale.common.ContactMethod getContactMethod()
   {
      return this.contactMethod;
   }

   public void setContactMethod(
         com.crossvale.common.ContactMethod contactMethod)
   {
      this.contactMethod = contactMethod;
   }

   public com.crossvale.common.Classification getClassification()
   {
      return this.classification;
   }

   public void setClassification(
         com.crossvale.common.Classification classification)
   {
      this.classification = classification;
   }

   public java.util.List<com.crossvale.common.Transaction> getTransactionList()
   {
      return this.transactionList;
   }

   public void setTransactionList(
         java.util.List<com.crossvale.common.Transaction> transactionList)
   {
      this.transactionList = transactionList;
   }

   public java.util.List<com.crossvale.common.Attribute> getAttributeList()
   {
      return this.attributeList;
   }

   public void setAttributeList(
         java.util.List<com.crossvale.common.Attribute> attributeList)
   {
      this.attributeList = attributeList;
   }

   public java.util.List<com.crossvale.common.Attachment> getAttachmentList()
   {
      return this.attachmentList;
   }

   public void setAttachmentList(
         java.util.List<com.crossvale.common.Attachment> attachmentList)
   {
      this.attachmentList = attachmentList;
   }

   public java.util.List<com.crossvale.common.Action> getActionList()
   {
      return this.actionList;
   }

   public void setActionList(
         java.util.List<com.crossvale.common.Action> actionList)
   {
      this.actionList = actionList;
   }

   public java.lang.String getSla()
   {
      return this.sla;
   }

   public void setSla(java.lang.String sla)
   {
      this.sla = sla;
   }

   public java.util.List<com.crossvale.common.Task> getTaskList()
   {
      return this.taskList;
   }

   public void setTaskList(java.util.List<com.crossvale.common.Task> taskList)
   {
      this.taskList = taskList;
   }

   public Ticket(java.lang.String ticketNumber, java.lang.String narrative,
         java.lang.String complaintFlag, java.lang.String approvalFlag,
         java.lang.String securityLevelCode, java.lang.String createdDate,
         java.lang.String receivedDate, com.crossvale.common.AssignTo assignTo,
         com.crossvale.common.Audit audit,
         com.crossvale.common.CodeValue category,
         com.crossvale.common.CodeValue item,
         com.crossvale.common.CodeValue status,
         com.crossvale.common.CodeValue severity,
         com.crossvale.common.CodeValue priority,
         com.crossvale.common.Originator originator,
         com.crossvale.common.Requestor requestor,
         com.crossvale.common.ContactMethod contactMethod,
         com.crossvale.common.Classification classification,
         java.util.List<com.crossvale.common.Transaction> transactionList,
         java.util.List<com.crossvale.common.Attribute> attributeList,
         java.util.List<com.crossvale.common.Attachment> attachmentList,
         java.util.List<com.crossvale.common.Action> actionList,
         java.lang.String sla, java.util.List<com.crossvale.common.Task> taskList)
   {
      this.ticketNumber = ticketNumber;
      this.narrative = narrative;
      this.complaintFlag = complaintFlag;
      this.approvalFlag = approvalFlag;
      this.securityLevelCode = securityLevelCode;
      this.createdDate = createdDate;
      this.receivedDate = receivedDate;
      this.assignTo = assignTo;
      this.audit = audit;
      this.category = category;
      this.item = item;
      this.status = status;
      this.severity = severity;
      this.priority = priority;
      this.originator = originator;
      this.requestor = requestor;
      this.contactMethod = contactMethod;
      this.classification = classification;
      this.transactionList = transactionList;
      this.attributeList = attributeList;
      this.attachmentList = attachmentList;
      this.actionList = actionList;
      this.sla = sla;
      this.taskList = taskList;
   }

}