package com.crossvale.common;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class TransactionDetails implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "type")
   private java.lang.String type;
   @org.kie.api.definition.type.Label(value = "description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label(value = "posted")
   private java.lang.String posted;
   @org.kie.api.definition.type.Label(value = "completed")
   private java.lang.String completed;

   public TransactionDetails()
   {
   }

   public java.lang.String getType()
   {
      return this.type;
   }

   public void setType(java.lang.String type)
   {
      this.type = type;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getPosted()
   {
      return this.posted;
   }

   public void setPosted(java.lang.String posted)
   {
      this.posted = posted;
   }

   public java.lang.String getCompleted()
   {
      return this.completed;
   }

   public void setCompleted(java.lang.String completed)
   {
      this.completed = completed;
   }

   public TransactionDetails(java.lang.String type,
         java.lang.String description, java.lang.String posted,
         java.lang.String completed)
   {
      this.type = type;
      this.description = description;
      this.posted = posted;
      this.completed = completed;
   }

}