package com.crossvale.carddispute;

rule "Question 1"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "1" )
	then
		modify( disputesQuestionnaire ){ setQuestion("Why are you submitting this dispute?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion()); 
		
end

rule "Question 2"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "2")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Were you advised of the refund or cancellation policy at the time of sale?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 3"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "3")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Please provide a description of the merchandise or services"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 4"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "4")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Do you have the receipt?"), setNextQuestionCode("N/A")};
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 5"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "5")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Do you have the receipt, cancelled check or other bank card statement?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 6"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "6")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Was it a cancellation or a return?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 7"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "7")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you cancel the purchase?"), setNextQuestionCode("8") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 8"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "8")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What was the reason for the cancellation?"), setNextQuestionCode("9") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 9"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "9")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Did the merchant provide a cancellation number?"), setNextQuestionCode("10") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 10"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "10")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Please provide the cancellation number. (Answer n/a if you do not have this information available.)"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 11"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "11")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Was it returned by a carrier? (FedEx, UPS, etc.)"), setNextQuestionCode("12") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 12"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "12")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you return the merchandise?"), setNextQuestionCode("13") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 13"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "13")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Please provide the carrier name and tracking number. (Answer n/a if you do not have this information available.)"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 14"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "14")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Did you attempt to contact the merchant to resolve the issue?"), setNextQuestionCode("15") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 15"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "15")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you contact the merchant?"), setNextQuestionCode("16") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 16"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "16")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What was the merchants's response?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 17"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "17")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you receive the merchandise or services?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 18"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "18")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Please explain what was wrong with the merchandise or services."), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 19"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "19")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Have you returned the merchandise? Note: If this was a service-related transaction, select n/a."), setNextQuestionCode("20") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 20"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "20")
	then
	    modify( disputesQuestionnaire ){ setQuestion("When and how was the merchandise returned?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 21"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "21")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Are you currently in possession of the merchandise?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 22"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "22")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Could the extra amount be due to one of the following?<br/> * Tip<br/> * Surcharge from a hotel, rental car or cruise line<br/> * Currency conversion difference"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 23"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "23")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Do you still wish to dispute all or part of the transaction(s)?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 24"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "24")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What is the amount you should have been charged?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 26"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "25")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What is the date of the original transaction?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 27"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "26")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What is the amount of the original transaction?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 28"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "27")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What was the alternate means of payment?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 29"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "28")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you expect to receive the merchandise or services?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 30"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "29")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Please provide a description of the merchandise or services expected. If your order was partially filled, please describe the merchandise or services received."), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 31"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "30")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Does everyone listed on the account have their card(s)?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 32"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "31")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you realize the card(s) were missing?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 33"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "32")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you last use the card(s)?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 34"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "33")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you discover the fraudulent charges?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 35"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "34")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Have you given your card or PIN to anyone?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 36"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "35")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Who would have access to the card(s)?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 37"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "36")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Are any of the following conditions applicable to the transaction(s)?<br/> * I recognize part of the transaction(s)<br/> * I have recently done business with the merchant(s)<br/> * I have attended an event where the merchant(s) may have been operating under a different name<br/> * I have regularly occurring charges from the merchant(s)"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 38"
	no-loop true
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( questionCode == "37")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Based on the reason selected, you indicate that this may be a fraudulent transaction. If you complete the dispute process and receive confirmation, your card(s) will be closed and new card(s) will be mailed to you. Do you wish to continue?"), setNextQuestionCode("N/A") };
		System.out.println(disputesQuestionnaire.getQuestion());
end
