package com.crossvale.carddispute;


rule "Question 1"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "1" )
	then
		modify( disputesQuestionnaire ){ setQuestion("Why are you submitting this dispute?") };
		System.out.println(disputesQuestionnaire.getQuestion()); 
		
end

rule "Question 2"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "2")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Were you advised of the refund or cancellation policy at the time of sale?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 3"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "3")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Please provide a description of the merchandise or services") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 4"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "4")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Do you have the receipt?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 5"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "5")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Do you have the receipt, cancelled check or other bank card statement?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 6"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "6")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Was it a cancellation or a return?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 7"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "7")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you cancel the purchase?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 8"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "8")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What was the reason for the cancellation?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 9"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "9")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Did the merchant provide a cancellation number?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 10"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "10")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Please provide the cancellation number. (Answer n/a if you do not have this information available.)") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 11"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "11")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Was it returned by a carrier? (FedEx, UPS, etc.)") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 12"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "12")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you return the merchandise?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 13"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "13")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Please provide the carrier name and tracking number. (Answer n/a if you do not have this information available.)") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 14"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "14")
	then
	    modify( disputesQuestionnaire ){ setQuestion("Did you attempt to contact the merchant to resolve the issue?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end

rule "Question 15"
	no-loop true
	ruleflow-group "disputes"
	dialect "mvel"
	when
		disputesQuestionnaire : Questionnaire( answerCode == "15")
	then
	    modify( disputesQuestionnaire ){ setQuestion("What date did you contact the merchant?") };
		System.out.println(disputesQuestionnaire.getQuestion());
end