package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Account implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "accountNumber")
   private java.lang.String accountNumber;
   @org.kie.api.definition.type.Label(value = "customerNumber")
   private java.lang.String customerNumber;
   @org.kie.api.definition.type.Label(value = "accountName")
   private java.lang.String accountName;
   @org.kie.api.definition.type.Label(value = "accountType")
   private java.lang.String accountType;
   @org.kie.api.definition.type.Label(value = "available")
   private java.lang.Float available;
   @org.kie.api.definition.type.Label(value = "posted")
   private java.lang.Float posted;
   @org.kie.api.definition.type.Label(value = "status")
   private java.lang.String status;

   public Account()
   {
   }

   public java.lang.String getAccountNumber()
   {
      return this.accountNumber;
   }

   public void setAccountNumber(java.lang.String accountNumber)
   {
      this.accountNumber = accountNumber;
   }

   public java.lang.String getCustomerNumber()
   {
      return this.customerNumber;
   }

   public void setCustomerNumber(java.lang.String customerNumber)
   {
      this.customerNumber = customerNumber;
   }

   public java.lang.String getAccountName()
   {
      return this.accountName;
   }

   public void setAccountName(java.lang.String accountName)
   {
      this.accountName = accountName;
   }

   public java.lang.String getAccountType()
   {
      return this.accountType;
   }

   public void setAccountType(java.lang.String accountType)
   {
      this.accountType = accountType;
   }

   public java.lang.Float getAvailable()
   {
      return this.available;
   }

   public void setAvailable(java.lang.Float available)
   {
      this.available = available;
   }

   public java.lang.Float getPosted()
   {
      return this.posted;
   }

   public void setPosted(java.lang.Float posted)
   {
      this.posted = posted;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public Account(java.lang.String accountNumber,
         java.lang.String customerNumber, java.lang.String accountName,
         java.lang.String accountType, java.lang.Float available,
         java.lang.Float posted, java.lang.String status)
   {
      this.accountNumber = accountNumber;
      this.customerNumber = customerNumber;
      this.accountName = accountName;
      this.accountType = accountType;
      this.available = available;
      this.posted = posted;
      this.status = status;
   }

}