package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Actions implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Actions() {
    }

}