package com.crossvale.carddispute;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Action")
public class Action implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("actionNumber")
   private java.lang.String actionNumber;
   @org.kie.api.definition.type.Label("actionTime")
   private Date actionTime;
   @org.kie.api.definition.type.Label("username")
   private java.lang.String username;
   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("description")
   private java.lang.String description;
   @org.kie.api.definition.type.Label("customInfo")
   private java.lang.String customInfo;

   @org.kie.api.definition.type.Label(value = "actionCode")
   private java.lang.String actionCode;

   @org.kie.api.definition.type.Label(value = "globalId")
   private java.lang.String globalId;

   @org.kie.api.definition.type.Label(value = "narrative")
   private java.lang.String narrative;

   @org.kie.api.definition.type.Label(value = "statusFlag")
   private java.lang.String statusFlag;

   @org.kie.api.definition.type.Label(value = "assignTo")
   private com.crossvale.carddispute.AssignTo assignTo;

   @org.kie.api.definition.type.Label(value = "level")
   private com.crossvale.carddispute.CodeValue level;

   @org.kie.api.definition.type.Label(value = "type")
   private com.crossvale.carddispute.CodeValue type;

   public Action()
   {
   }

   public java.lang.String getActionNumber()
   {
      return this.actionNumber;
   }

   public void setActionNumber(java.lang.String actionNumber)
   {
      this.actionNumber = actionNumber;
   }

   public java.lang.String getUsername()
   {
      return this.username;
   }

   public void setUsername(java.lang.String username)
   {
      this.username = username;
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getDescription()
   {
      return this.description;
   }

   public void setDescription(java.lang.String description)
   {
      this.description = description;
   }

   public java.lang.String getCustomInfo()
   {
      return this.customInfo;
   }

   public void setCustomInfo(java.lang.String customInfo)
   {
      this.customInfo = customInfo;
   }

   public java.util.Date getActionTime()
   {
      return this.actionTime;
   }

   public void setActionTime(java.util.Date actionTime)
   {
      this.actionTime = actionTime;
   }

   public java.lang.String getActionCode()
   {
      return this.actionCode;
   }

   public void setActionCode(java.lang.String actionCode)
   {
      this.actionCode = actionCode;
   }

   public java.lang.String getGlobalId()
   {
      return this.globalId;
   }

   public void setGlobalId(java.lang.String globalId)
   {
      this.globalId = globalId;
   }

   public java.lang.String getNarrative()
   {
      return this.narrative;
   }

   public void setNarrative(java.lang.String narrative)
   {
      this.narrative = narrative;
   }

   public java.lang.String getStatusFlag()
   {
      return this.statusFlag;
   }

   public void setStatusFlag(java.lang.String statusFlag)
   {
      this.statusFlag = statusFlag;
   }

   public com.crossvale.carddispute.AssignTo getAssignTo()
   {
      return this.assignTo;
   }

   public void setAssignTo(com.crossvale.carddispute.AssignTo assignTo)
   {
      this.assignTo = assignTo;
   }

   public com.crossvale.carddispute.CodeValue getLevel()
   {
      return this.level;
   }

   public void setLevel(com.crossvale.carddispute.CodeValue level)
   {
      this.level = level;
   }

   public com.crossvale.carddispute.CodeValue getType()
   {
      return this.type;
   }

   public void setType(com.crossvale.carddispute.CodeValue type)
   {
      this.type = type;
   }

   public Action(java.lang.String actionNumber, java.util.Date actionTime,
         java.lang.String username, java.lang.String ticketNumber,
         java.lang.String description, java.lang.String customInfo,
         java.lang.String actionCode, java.lang.String globalId,
         java.lang.String narrative, java.lang.String statusFlag,
         com.crossvale.carddispute.AssignTo assignTo,
         com.crossvale.carddispute.CodeValue level,
         com.crossvale.carddispute.CodeValue type)
   {
      this.actionNumber = actionNumber;
      this.actionTime = actionTime;
      this.username = username;
      this.ticketNumber = ticketNumber;
      this.description = description;
      this.customInfo = customInfo;
      this.actionCode = actionCode;
      this.globalId = globalId;
      this.narrative = narrative;
      this.statusFlag = statusFlag;
      this.assignTo = assignTo;
      this.level = level;
      this.type = type;
   }

}