package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AssignTo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "user")
   private com.crossvale.carddispute.CodeValue user;
   @org.kie.api.definition.type.Label(value = "group")
   private com.crossvale.carddispute.CodeValue group;

   public AssignTo()
   {
   }

   public com.crossvale.carddispute.CodeValue getUser()
   {
      return this.user;
   }

   public void setUser(com.crossvale.carddispute.CodeValue user)
   {
      this.user = user;
   }

   public com.crossvale.carddispute.CodeValue getGroup()
   {
      return this.group;
   }

   public void setGroup(com.crossvale.carddispute.CodeValue group)
   {
      this.group = group;
   }

   public AssignTo(com.crossvale.carddispute.CodeValue user,
         com.crossvale.carddispute.CodeValue group)
   {
      this.user = user;
      this.group = group;
   }

}