package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DisputeRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Fraud")
   private java.lang.String fraud;

   public DisputeRequest()
   {
   }

   public java.lang.String getFraud()
   {
      return this.fraud;
   }

   public void setFraud(java.lang.String fraud)
   {
      this.fraud = fraud;
   }

   public DisputeRequest(java.lang.String fraud)
   {
      this.fraud = fraud;
   }

}