package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("DisputeRequest")
public class DisputeRequest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("Fraud")
   private java.lang.String fraud;

   @org.kie.api.definition.type.Label("Amount")
   private Float amount;

   @org.kie.api.definition.type.Label("Chargeback")
   private java.lang.String chargeback;

   @org.kie.api.definition.type.Label("CustomerType")
   private java.lang.String customerType;

   public DisputeRequest()
   {
   }

   public java.lang.String getFraud()
   {
      return this.fraud;
   }

   public void setFraud(java.lang.String fraud)
   {
      this.fraud = fraud;
   }

   public java.lang.String getChargeback()
   {
      return this.chargeback;
   }

   public void setChargeback(java.lang.String chargeback)
   {
      this.chargeback = chargeback;
   }

   public java.lang.Float getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Float amount)
   {
      this.amount = amount;
   }

   public java.lang.String getCustomerType()
   {
      return this.customerType;
   }

   public void setCustomerType(java.lang.String customerType)
   {
      this.customerType = customerType;
   }

   public DisputeRequest(java.lang.String fraud, java.lang.Float amount,
         java.lang.String chargeback, java.lang.String customerType)
   {
      this.fraud = fraud;
      this.amount = amount;
      this.chargeback = chargeback;
      this.customerType = customerType;
   }

}