package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("PhoneNr")
public class PhoneNr implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public PhoneNr()
   {
   }

}