package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
public class Questionnaire implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("question")
   private java.lang.String question;
   @org.kie.api.definition.type.Label("nextQuestionCode")
   private java.lang.String nextQuestionCode;

   @org.kie.api.definition.type.Label("questionCode")
   private java.lang.String questionCode;

   public Questionnaire()
   {
   }

   public java.lang.String getQuestion()
   {
      return this.question;
   }

   public void setQuestion(java.lang.String question)
   {
      this.question = question;
   }

   public java.lang.String getNextQuestionCode()
   {
      return this.nextQuestionCode;
   }

   public void setNextQuestionCode(java.lang.String nextQuestionCode)
   {
      this.nextQuestionCode = nextQuestionCode;
   }

   public java.lang.String getQuestionCode()
   {
      return this.questionCode;
   }

   public void setQuestionCode(java.lang.String questionCode)
   {
      this.questionCode = questionCode;
   }

   public Questionnaire(java.lang.String question,
         java.lang.String nextQuestionCode, java.lang.String questionCode)
   {
      this.question = question;
      this.nextQuestionCode = nextQuestionCode;
      this.questionCode = questionCode;
   }

}