package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.remote.Remotable
@org.kie.api.definition.type.Label("Questionnaire")
public class Questionnaire implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("question")
   private java.lang.String question;
   @org.kie.api.definition.type.Label("nextQuestionCode")
   private java.lang.String nextQuestionCode;

   @org.kie.api.definition.type.Label("questionCode")
   private java.lang.String questionCode;

   @org.kie.api.definition.type.Label("answer")
   private java.lang.String answer;

   @org.kie.api.definition.type.Label(value = "nextQuestion")
   private java.lang.String nextQuestion;

   public Questionnaire()
   {
   }

   public java.lang.String getQuestion()
   {
      return this.question;
   }

   public void setQuestion(java.lang.String question)
   {
      this.question = question;
   }

   public java.lang.String getNextQuestionCode()
   {
      return this.nextQuestionCode;
   }

   public void setNextQuestionCode(java.lang.String nextQuestionCode)
   {
      this.nextQuestionCode = nextQuestionCode;
   }

   public java.lang.String getQuestionCode()
   {
      return this.questionCode;
   }

   public void setQuestionCode(java.lang.String questionCode)
   {
      this.questionCode = questionCode;
   }

   public java.lang.String getAnswer()
   {
      return this.answer;
   }

   public void setAnswer(java.lang.String answer)
   {
      this.answer = answer;
   }

   public java.lang.String getNextQuestion()
   {
      return this.nextQuestion;
   }

   public void setNextQuestion(java.lang.String nextQuestion)
   {
      this.nextQuestion = nextQuestion;
   }

   public Questionnaire(java.lang.String question,
         java.lang.String nextQuestionCode, java.lang.String questionCode,
         java.lang.String answer, java.lang.String nextQuestion)
   {
      this.question = question;
      this.nextQuestionCode = nextQuestionCode;
      this.questionCode = questionCode;
      this.answer = answer;
      this.nextQuestion = nextQuestion;
   }

}