package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Task")
public class Task implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   public Task()
   {
   }

}