package com.crossvale.carddispute;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Task")
public class Task implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("taskNumber")
   private java.lang.String taskNumber;
   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label(value = "taskCode")
   private java.lang.String taskCode;

   @org.kie.api.definition.type.Label(value = "customData")
   private java.lang.String customData;

   @org.kie.api.definition.type.Label(value = "slaDate")
   private java.util.Date slaDate;

   @org.kie.api.definition.type.Label(value = "taskBpm")
   private java.lang.String taskBpm;

   @org.kie.api.definition.type.Label(value = "createdDate")
   private java.util.Date createdDate;

   @org.kie.api.definition.type.Label(value = "status")
   private com.crossvale.carddispute.CodeValue status;

   @org.kie.api.definition.type.Label(value = "assignTo")
   private com.crossvale.carddispute.AssignTo assignTo;

   @org.kie.api.definition.type.Label(value = "slaStatus")
   private com.crossvale.carddispute.CodeValue slaStatus;

   @org.kie.api.definition.type.Label(value = "audit")
   private com.crossvale.carddispute.Audit audit;

   public Task()
   {
   }

   public java.lang.String getTaskNumber()
   {
      return this.taskNumber;
   }

   public void setTaskNumber(java.lang.String taskNumber)
   {
      this.taskNumber = taskNumber;
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getTaskCode()
   {
      return this.taskCode;
   }

   public void setTaskCode(java.lang.String taskCode)
   {
      this.taskCode = taskCode;
   }

   public java.lang.String getCustomData()
   {
      return this.customData;
   }

   public void setCustomData(java.lang.String customData)
   {
      this.customData = customData;
   }

   public java.util.Date getSlaDate()
   {
      return this.slaDate;
   }

   public void setSlaDate(java.util.Date slaDate)
   {
      this.slaDate = slaDate;
   }

   public java.lang.String getTaskBpm()
   {
      return this.taskBpm;
   }

   public void setTaskBpm(java.lang.String taskBpm)
   {
      this.taskBpm = taskBpm;
   }

   public java.util.Date getCreatedDate()
   {
      return this.createdDate;
   }

   public void setCreatedDate(java.util.Date createdDate)
   {
      this.createdDate = createdDate;
   }

   public com.crossvale.carddispute.CodeValue getStatus()
   {
      return this.status;
   }

   public void setStatus(com.crossvale.carddispute.CodeValue status)
   {
      this.status = status;
   }

   public com.crossvale.carddispute.AssignTo getAssignTo()
   {
      return this.assignTo;
   }

   public void setAssignTo(com.crossvale.carddispute.AssignTo assignTo)
   {
      this.assignTo = assignTo;
   }

   public com.crossvale.carddispute.CodeValue getSlaStatus()
   {
      return this.slaStatus;
   }

   public void setSlaStatus(com.crossvale.carddispute.CodeValue slaStatus)
   {
      this.slaStatus = slaStatus;
   }

   public com.crossvale.carddispute.Audit getAudit()
   {
      return this.audit;
   }

   public void setAudit(com.crossvale.carddispute.Audit audit)
   {
      this.audit = audit;
   }

   public Task(java.lang.String taskNumber, java.lang.String ticketNumber,
         java.lang.String taskCode, java.lang.String customData,
         java.util.Date slaDate, java.lang.String taskBpm,
         java.util.Date createdDate, com.crossvale.carddispute.CodeValue status,
         com.crossvale.carddispute.AssignTo assignTo,
         com.crossvale.carddispute.CodeValue slaStatus,
         com.crossvale.carddispute.Audit audit)
   {
      this.taskNumber = taskNumber;
      this.ticketNumber = ticketNumber;
      this.taskCode = taskCode;
      this.customData = customData;
      this.slaDate = slaDate;
      this.taskBpm = taskBpm;
      this.createdDate = createdDate;
      this.status = status;
      this.assignTo = assignTo;
      this.slaStatus = slaStatus;
      this.audit = audit;
   }

}