package com.crossvale.carddispute;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Test implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Test")
   private java.lang.String test;

   public Test()
   {
   }

   public java.lang.String getTest()
   {
      return this.test;
   }

   public void setTest(java.lang.String test)
   {
      this.test = test;
   }

   public Test(java.lang.String test)
   {
      this.test = test;
   }

}