package com.crossvale.carddispute;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Ticket")
public class Ticket implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("narrative")
   private java.lang.String narrative;
   @org.kie.api.definition.type.Label("accountNumber")
   private java.lang.String accountNumber;
   @org.kie.api.definition.type.Label("customerNumber")
   private java.lang.String customerNumber;

   @org.kie.api.definition.type.Label("customer")
   private com.crossvale.carddispute.Customer customer;

   @org.kie.api.definition.type.Label("tasks")
   private java.util.List<com.crossvale.carddispute.Task> tasks;

   @org.kie.api.definition.type.Label("actions")
   private java.util.List<com.crossvale.carddispute.Action> actions;

   @org.kie.api.definition.type.Label(value = "complaintFlag")
   private java.lang.String complaintFlag;

   @org.kie.api.definition.type.Label(value = "approvalFlag")
   private java.lang.String approvalFlag;

   @org.kie.api.definition.type.Label(value = "securityLevelCode")
   private java.lang.String securityLevelCode;

   @org.kie.api.definition.type.Label(value = "createdDate")
   private java.util.Date createdDate;

   @org.kie.api.definition.type.Label(value = "receivedDate")
   private java.util.Date receivedDate;

   public Ticket()
   {
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getNarrative()
   {
      return this.narrative;
   }

   public void setNarrative(java.lang.String narrative)
   {
      this.narrative = narrative;
   }

   public java.lang.String getAccountNumber()
   {
      return this.accountNumber;
   }

   public void setAccountNumber(java.lang.String accountNumber)
   {
      this.accountNumber = accountNumber;
   }

   public java.lang.String getCustomerNumber()
   {
      return this.customerNumber;
   }

   public void setCustomerNumber(java.lang.String customerNumber)
   {
      this.customerNumber = customerNumber;
   }

   public com.crossvale.carddispute.Customer getCustomer()
   {
      return this.customer;
   }

   public void setCustomer(com.crossvale.carddispute.Customer customer)
   {
      this.customer = customer;
   }

   public java.util.List<com.crossvale.carddispute.Task> getTasks()
   {
      return this.tasks;
   }

   public void setTasks(java.util.List<com.crossvale.carddispute.Task> tasks)
   {
      this.tasks = tasks;
   }

   public java.util.List<com.crossvale.carddispute.Action> getActions()
   {
      return this.actions;
   }

   public void setActions(java.util.List<com.crossvale.carddispute.Action> actions)
   {
      this.actions = actions;
   }

   public java.lang.String getComplaintFlag()
   {
      return this.complaintFlag;
   }

   public void setComplaintFlag(java.lang.String complaintFlag)
   {
      this.complaintFlag = complaintFlag;
   }

   public java.lang.String getApprovalFlag()
   {
      return this.approvalFlag;
   }

   public void setApprovalFlag(java.lang.String approvalFlag)
   {
      this.approvalFlag = approvalFlag;
   }

   public java.lang.String getSecurityLevelCode()
   {
      return this.securityLevelCode;
   }

   public void setSecurityLevelCode(java.lang.String securityLevelCode)
   {
      this.securityLevelCode = securityLevelCode;
   }

   public java.util.Date getCreatedDate()
   {
      return this.createdDate;
   }

   public void setCreatedDate(java.util.Date createdDate)
   {
      this.createdDate = createdDate;
   }

   public java.util.Date getReceivedDate()
   {
      return this.receivedDate;
   }

   public void setReceivedDate(java.util.Date receivedDate)
   {
      this.receivedDate = receivedDate;
   }

   public Ticket(java.lang.String ticketNumber, java.lang.String narrative,
         java.lang.String accountNumber, java.lang.String customerNumber,
         com.crossvale.carddispute.Customer customer,
         java.util.List<com.crossvale.carddispute.Task> tasks,
         java.util.List<com.crossvale.carddispute.Action> actions,
         java.lang.String complaintFlag, java.lang.String approvalFlag,
         java.lang.String securityLevelCode, java.util.Date createdDate,
         java.util.Date receivedDate)
   {
      this.ticketNumber = ticketNumber;
      this.narrative = narrative;
      this.accountNumber = accountNumber;
      this.customerNumber = customerNumber;
      this.customer = customer;
      this.tasks = tasks;
      this.actions = actions;
      this.complaintFlag = complaintFlag;
      this.approvalFlag = approvalFlag;
      this.securityLevelCode = securityLevelCode;
      this.createdDate = createdDate;
      this.receivedDate = receivedDate;
   }

}