package com.crossvale.carddispute;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Ticket")
public class Ticket implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("dateReceived")
   private String dateReceived;
   @org.kie.api.definition.type.Label("source")
   private java.lang.String source;
   @org.kie.api.definition.type.Label("narrative")
   private java.lang.String narrative;
   @org.kie.api.definition.type.Label("accountNumber")
   private java.lang.String accountNumber;
   @org.kie.api.definition.type.Label("issue")
   private java.lang.String issue;
   @org.kie.api.definition.type.Label("customerNumber")
   private java.lang.String customerNumber;

   @org.kie.api.definition.type.Label("groupAssigned")
   private java.lang.String groupAssigned;

   @org.kie.api.definition.type.Label("dueDate")
   private java.util.Date dueDate;

   @org.kie.api.definition.type.Label("status")
   private java.lang.String status;

   @org.kie.api.definition.type.Label("customer")
   private com.crossvale.carddispute.Customer customer;

   @org.kie.api.definition.type.Label("tasks")
   private java.util.List<com.crossvale.carddispute.Task> tasks;

   @org.kie.api.definition.type.Label("actions")
   private java.util.List<com.crossvale.carddispute.Action> actions;

   public Ticket()
   {
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getSource()
   {
      return this.source;
   }

   public void setSource(java.lang.String source)
   {
      this.source = source;
   }

   public java.lang.String getNarrative()
   {
      return this.narrative;
   }

   public void setNarrative(java.lang.String narrative)
   {
      this.narrative = narrative;
   }

   public java.lang.String getAccountNumber()
   {
      return this.accountNumber;
   }

   public void setAccountNumber(java.lang.String accountNumber)
   {
      this.accountNumber = accountNumber;
   }

   public java.lang.String getIssue()
   {
      return this.issue;
   }

   public void setIssue(java.lang.String issue)
   {
      this.issue = issue;
   }

   public java.lang.String getCustomerNumber()
   {
      return this.customerNumber;
   }

   public void setCustomerNumber(java.lang.String customerNumber)
   {
      this.customerNumber = customerNumber;
   }

   public java.lang.String getGroupAssigned()
   {
      return this.groupAssigned;
   }

   public void setGroupAssigned(java.lang.String groupAssigned)
   {
      this.groupAssigned = groupAssigned;
   }

   public java.util.Date getDueDate()
   {
      return this.dueDate;
   }

   public void setDueDate(java.util.Date dueDate)
   {
      this.dueDate = dueDate;
   }

   public java.lang.String getStatus()
   {
      return this.status;
   }

   public void setStatus(java.lang.String status)
   {
      this.status = status;
   }

   public com.crossvale.carddispute.Customer getCustomer()
   {
      return this.customer;
   }

   public void setCustomer(com.crossvale.carddispute.Customer customer)
   {
      this.customer = customer;
   }

   public java.util.List<com.crossvale.carddispute.Task> getTasks()
   {
      return this.tasks;
   }

   public void setTasks(java.util.List<com.crossvale.carddispute.Task> tasks)
   {
      this.tasks = tasks;
   }

   public java.util.List<com.crossvale.carddispute.Action> getActions()
   {
      return this.actions;
   }

   public void setActions(java.util.List<com.crossvale.carddispute.Action> actions)
   {
      this.actions = actions;
   }

   public java.lang.String getDateReceived()
   {
      return this.dateReceived;
   }

   public void setDateReceived(java.lang.String dateReceived)
   {
      this.dateReceived = dateReceived;
   }

   public Ticket(java.lang.String ticketNumber, java.lang.String dateReceived,
         java.lang.String source, java.lang.String narrative,
         java.lang.String accountNumber, java.lang.String issue,
         java.lang.String customerNumber, java.lang.String groupAssigned,
         java.util.Date dueDate, java.lang.String status,
         com.crossvale.carddispute.Customer customer,
         java.util.List<com.crossvale.carddispute.Task> tasks,
         java.util.List<com.crossvale.carddispute.Action> actions)
   {
      this.ticketNumber = ticketNumber;
      this.dateReceived = dateReceived;
      this.source = source;
      this.narrative = narrative;
      this.accountNumber = accountNumber;
      this.issue = issue;
      this.customerNumber = customerNumber;
      this.groupAssigned = groupAssigned;
      this.dueDate = dueDate;
      this.status = status;
      this.customer = customer;
      this.tasks = tasks;
      this.actions = actions;
   }

}