package com.crossvale.carddispute;

import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Ticket implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("ticketNumber")
   private java.lang.String ticketNumber;
   @org.kie.api.definition.type.Label("dateReceived")
   private Date dateReceived;
   @org.kie.api.definition.type.Label("source")
   private java.lang.String source;
   @org.kie.api.definition.type.Label("representative")
   private java.lang.String representative;
   @org.kie.api.definition.type.Label("customerName")
   private java.lang.String customerName;
   @org.kie.api.definition.type.Label("preferredContact")
   private java.lang.String preferredContact;
   @org.kie.api.definition.type.Label("preferredContactMethod")
   private java.lang.String preferredContactMethod;
   @org.kie.api.definition.type.Label("preferredContactLanguage")
   private java.lang.String preferredContactLanguage;
   @org.kie.api.definition.type.Label("narrative")
   private java.lang.String narrative;
   @org.kie.api.definition.type.Label("accountNumber")
   private java.lang.String accountNumber;
   @org.kie.api.definition.type.Label("issue")
   private java.lang.String issue;
   @org.kie.api.definition.type.Label("reason")
   private java.lang.String reason;

   public Ticket()
   {
   }

   public java.lang.String getTicketNumber()
   {
      return this.ticketNumber;
   }

   public void setTicketNumber(java.lang.String ticketNumber)
   {
      this.ticketNumber = ticketNumber;
   }

   public java.lang.String getSource()
   {
      return this.source;
   }

   public void setSource(java.lang.String source)
   {
      this.source = source;
   }

   public java.lang.String getRepresentative()
   {
      return this.representative;
   }

   public void setRepresentative(java.lang.String representative)
   {
      this.representative = representative;
   }

   public java.lang.String getCustomerName()
   {
      return this.customerName;
   }

   public void setCustomerName(java.lang.String customerName)
   {
      this.customerName = customerName;
   }

   public java.lang.String getPreferredContact()
   {
      return this.preferredContact;
   }

   public void setPreferredContact(java.lang.String preferredContact)
   {
      this.preferredContact = preferredContact;
   }

   public java.lang.String getPreferredContactMethod()
   {
      return this.preferredContactMethod;
   }

   public void setPreferredContactMethod(
         java.lang.String preferredContactMethod)
   {
      this.preferredContactMethod = preferredContactMethod;
   }

   public java.lang.String getPreferredContactLanguage()
   {
      return this.preferredContactLanguage;
   }

   public void setPreferredContactLanguage(
         java.lang.String preferredContactLanguage)
   {
      this.preferredContactLanguage = preferredContactLanguage;
   }

   public java.lang.String getNarrative()
   {
      return this.narrative;
   }

   public void setNarrative(java.lang.String narrative)
   {
      this.narrative = narrative;
   }

   public java.lang.String getAccountNumber()
   {
      return this.accountNumber;
   }

   public void setAccountNumber(java.lang.String accountNumber)
   {
      this.accountNumber = accountNumber;
   }

   public java.lang.String getIssue()
   {
      return this.issue;
   }

   public void setIssue(java.lang.String issue)
   {
      this.issue = issue;
   }

   public java.lang.String getReason()
   {
      return this.reason;
   }

   public void setReason(java.lang.String reason)
   {
      this.reason = reason;
   }

   public java.util.Date getDateReceived()
   {
      return this.dateReceived;
   }

   public void setDateReceived(java.util.Date dateReceived)
   {
      this.dateReceived = dateReceived;
   }

   public Ticket(java.lang.String ticketNumber, java.util.Date dateReceived,
         java.lang.String source, java.lang.String representative,
         java.lang.String customerName, java.lang.String preferredContact,
         java.lang.String preferredContactMethod,
         java.lang.String preferredContactLanguage, java.lang.String narrative,
         java.lang.String accountNumber, java.lang.String issue,
         java.lang.String reason)
   {
      this.ticketNumber = ticketNumber;
      this.dateReceived = dateReceived;
      this.source = source;
      this.representative = representative;
      this.customerName = customerName;
      this.preferredContact = preferredContact;
      this.preferredContactMethod = preferredContactMethod;
      this.preferredContactLanguage = preferredContactLanguage;
      this.narrative = narrative;
      this.accountNumber = accountNumber;
      this.issue = issue;
      this.reason = reason;
   }

}